# Generated by Django 4.0.3 on 2022-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='design_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='usability_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
