# Generated by Django 4.0.3 on 2022-03-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_alter_project_content_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
