# Generated by Django 4.0.3 on 2022-03-14 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0007_alter_project_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content_score',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_score',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='usability_score',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
